function [montMat] = TCPMont(valueMat)
%UNTITLED11 Summary of this function goes here
%   Detailed explanation goes here
montMat = zeros(height(valueMat),width(valueMat));
FP1 = 1;
FP2 = 2;
F3 = 3;
F4 = 4;
C3 = 5;
C4 = 6;
A1 = 7;
A2 = 8;
P3 = 9;
P4 = 10;
O1 = 11;
O2 = 12;
F7 = 13;
F8 = 14;
T3 = 15;
T4 = 16;
T5 = 17;
T6 = 18;
FZ = 19;
CZ = 20;
PZ = 21;
OZ = 22;
montMat(:,1) = valueMat(:,FP1) - valueMat(:,F7); 
montMat(:,2) = valueMat(:,F7) - valueMat(:,T3); 
montMat(:,3) = valueMat(:,T3) - valueMat(:,T5);
montMat(:,4) = valueMat(:,T5) - valueMat(:,O1);
montMat(:,5) = valueMat(:,FP2) - valueMat(:,F8);
montMat(:,6) = valueMat(:,F8) - valueMat(:,T4);
montMat(:,7) = valueMat(:,T4) - valueMat(:,T6);
montMat(:,8) = valueMat(:,T6) - valueMat(:,O2);
montMat(:,9) = valueMat(:,A1) - valueMat(:,T3);
montMat(:,10) = valueMat(:,T3) - valueMat(:,C3);
montMat(:,11) = valueMat(:,C3) - valueMat(:,CZ);
montMat(:,12) = valueMat(:,CZ) - valueMat(:,C4);
montMat(:,13) = valueMat(:,C4) - valueMat(:,T4);
montMat(:,14) = valueMat(:,T4) - valueMat(:,A2);
montMat(:,15) = valueMat(:,FP1) - valueMat(:,F3);
montMat(:,16) = valueMat(:,F3) - valueMat(:,C3);
montMat(:,17) = valueMat(:,C3) - valueMat(:,P3);
montMat(:,18) = valueMat(:,P3) - valueMat(:,O1);
montMat(:,19) = valueMat(:,FP2) - valueMat(:,F4);
montMat(:,20) = valueMat(:,F4) - valueMat(:,C4);
montMat(:,21) = valueMat(:,C4) - valueMat(:,P4);
montMat(:,22) = valueMat(:,P4) - valueMat(:,O2);
end